### ISSUE TITLE
Remove duplicate tests

### ISSUE THREAD

**Issue by Phoscur** [ugml/api#63]
https://github.com/ugml/api/blob/60452b603ed86840cc328b54bc95e59142294ae0/src/routes/PlayersRouter.spec.ts#L118

Rather than just duplicating test code you should create a testcase which creates multiple players, if one is not enough, tests are not supposed to seed the database @mamen.
Keep in mind that you also need the test to be easily repeatable (deleting players afterwards)!
Also you need to see tests fail, which can only done properly before having an implementation.. time to go TDD ;)

Related to #30

**Comment by mamen** [comment]
These tests are intentionally duplicated to test all current lines of the player-creation-process. As soon as all data-access functionallity is moved into seperate service-classes, we can mock the database-access and simplify these test :)

You are right, post-test cleanup has to be implemented. I didn't bother, because for each build, travis resets the database to its initial state.

**Comment by Phoscur** [comment]
Alright, you may keep them if you call out different scenarios, currently it's the same scenario multiple times with the same name :P 

This might be a feature ticket if it implements player deletion.

**Comment by mamen** [comment]
I've removed the duplicate tests. With the new IoC-Container @Phoscur and I have created, the underlying problem should be fixed. This issue can be closed, after #65 is merged.
